# Generated by Django 2.1 on 2018-08-28 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('NumeroDossier', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('IndexPatient', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('NomPatient', models.CharField(max_length=250)),
                ('SexePatient', models.CharField(max_length=32)),
                ('NumTelephone', models.CharField(max_length=32)),
                ('AdressePatient', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('CodeService', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('NomService', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='dossier',
            name='IndexPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Service'),
        ),
    ]
