# Generated by Django 2.1 on 2018-09-05 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroDossier', models.IntegerField(verbose_name='Numero Dossier')),
                ('AnneeDossier', models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018)], default=2018, verbose_name='AnneeDossier')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('IndexPatient', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Index Patient')),
                ('NomPatient', models.CharField(max_length=250, verbose_name='Nom')),
                ('SexePatient', models.CharField(max_length=32, verbose_name='Sexe')),
                ('NumTelephone', models.CharField(max_length=32, verbose_name='Numero telephone')),
                ('AdressePatient', models.CharField(max_length=250, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeService', models.CharField(max_length=16, unique=True, verbose_name='Code Service')),
                ('NomService', models.CharField(max_length=250, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service',
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='IndexPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient', verbose_name='Index Patient'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Service', verbose_name='Code Service'),
        ),
        migrations.AlterUniqueTogether(
            name='dossier',
            unique_together={('NumeroDossier', 'AnneeDossier')},
        ),
    ]
