# Generated by Django 2.1 on 2018-09-05 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroDossier', models.CharField(max_length=32, verbose_name='Numero Dossier')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('IndexPatient', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Index Patient')),
                ('NomPatient', models.CharField(max_length=250, verbose_name='Nom')),
                ('SexePatient', models.CharField(max_length=32, verbose_name='Sexe')),
                ('NumTelephone', models.CharField(max_length=32, verbose_name='Numero telephone')),
                ('AdressePatient', models.CharField(max_length=250, verbose_name='Adresse')),
            ],
            options={
                'verbose_name': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeService', models.CharField(max_length=16, unique=True, verbose_name='Code Service')),
                ('NomService', models.CharField(max_length=250, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service',
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='IndexPatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient', verbose_name='Index Patient'),
        ),
        migrations.AddField(
            model_name='dossier',
            name='Service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Service', verbose_name='Code Service'),
        ),
    ]
